baseURL = "https://forpetswithlove.com/"
languageCode = "en-us"
title = "For Pets With Love! Everything you want for your pet's needs."
theme = "vex-hugo"

# Enable sitemap generation
[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

# Add outputs for proper sitemap generation
[outputs]
  home = ["HTML", "RSS", "JSON", "SITEMAP"]

[outputFormats.SITEMAP]
  mediaType = "application/xml"
  baseName = "sitemap"
  isHTML = false
