[build]
  publish = "public" # Standard Hugo output directory
  command = "hugo --gc --minify" # Build from root

[build.environment]
  HUGO_VERSION = "0.111.3" # Update Hugo version
  # HUGO_THEME = "repo" # Remove conflicting theme variable
  # Rely on baseurl set in exampleSite/config.toml

# Optional: Set the branch to deploy
[build.branch]
  production = "main" # Change this to your main branch if different

# Optional: Set the context for different environments
[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview.environment]
  HUGO_ENV = "preview"

