[build]
  publish = "exampleSite/public"
  command = "cd exampleSite && hugo --gc --minify --themesDir ../.. && hugo --gc --minify --themesDir ../.. > public/index.json"

[build.environment]
  HUGO_VERSION = "0.73.0"
  HUGO_THEME = "repo" # Explicitly set the theme
  # Rely on baseurl set in exampleSite/config.toml

# Optional: Set the branch to deploy
[build.branch]
  production = "main" # Change this to your main branch if different

# Optional: Set the context for different environments
[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview.environment]
  HUGO_ENV = "preview"

[[redirects]]
  from = "/search"
  to = "/search/"
  status = 301
