[build]
  publish = "exampleSite/public"
  # Run hugo from root, specifying source. Theme files in root should be found automatically.
  command = "hugo --gc --minify --source exampleSite"

[build.environment]
  HUGO_VERSION = "0.73.0"
  HUGO_THEME = "repo" # Ensure this is the correct theme name
  # Rely on baseurl set in exampleSite/config.toml

# Optional: Set the branch to deploy
[build.branch]
  production = "main" # Change this to your main branch if different

# Optional: Set the context for different environments
[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview.environment]
  HUGO_ENV = "preview"
