[build]
  publish = "exampleSite/public"
  command = "cd exampleSite && hugo --gc --minify --themesDir ../.."

[build.environment]
  HUGO_VERSION = "0.73.0"
  HUGO_THEME = "repo" # Ensure this is the correct theme name
  HUGO_BASEURL = "/"  # Adjust this if your site is hosted in a subdirectory

# Optional: Set the branch to deploy
[build.branch]
  production = "main" # Change this to your main branch if different

# Optional: Set the context for different environments
[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview.environment]
  HUGO_ENV = "preview"